### ISSUE TITLE
Provide Docker Compose for deploying a Prometheus-Grafana-StatsD stack

### ISSUE THREAD

**Issue by peterkingsbury** [stormwarestudios/godot-statsd-client#4]
Currently it is necessary for any consumers of this repository to manually assemble a StatsD-consuming stack in order to verify functionality.

A future update may include a Wiki page or deployable content in the repository, which might look like the following:

`docker-compose.yml`:
```yml
version: '3.3'

services:
  statsd:
    image: prom/statsd-exporter:v0.22.5
    ports:
      - "8125:8125/udp"
      - "9123:9102"
    command:
      - --statsd.listen-udp=:8125
      - --web.listen-address=:9102
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.35.0
    ports:
      - "5090:9090"
    links:
      - statsd
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --log.level=debug
      - --web.listen-address=:9090
      - --web.page-title='Prometheus'
    restart: unless-stopped

  grafana:
    image: grafana/grafana:8.5.2
    links:
      - prometheus
    ports:
      - "3000:3000"
    restart: unless-stopped
```

`prometheus.yml`:
```yml
global:
  scrape_interval:      5s
  evaluation_interval:  5s

scrape_configs:
  # optional: this makes the metrics available to us about Prometheus itself.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # tells Prometheus to scrape metrics an address over port 9123
  - job_name: 'statsd'
    static_configs:
      - targets: ['statsd:9102'] # see statsd-exporter further down
        labels: {'host': 'statsd'} # optional: just a way to identify the system exposing metrics
```
